# Generated by Django 5.2.11 on 2026-03-23 14:43

import django.db.migrations.operations.special
import django.db.models.deletion
from django.db import migrations, models

import objects.token.validators


class Migration(migrations.Migration):
    replaces = [
        ("token", "0001_initial"),
        ("token", "0002_auto_20201223_1231"),
        ("token", "0003_auto_20210312_1507"),
        ("token", "0004_auto_20210315_1537"),
        ("token", "0005_auto_20210623_1242"),
        ("token", "0006_auto_20210721_1543"),
        ("token", "0007_remove_permission_fields"),
        ("token", "0008_permission_fields"),
        ("token", "0009_alter_permission_fields"),
        ("token", "0010_tokenauth_is_superuser"),
        ("token", "0011_rename_tokenauth_oldtokenauth_and_more"),
        ("token", "0012_tokenauth_permission_token_auth"),
        ("token", "0013_copy_token_auth"),
        ("token", "0014_alter_permission_unique_together_and_more"),
        ("token", "0015_rename_new_token_auth_permission_token_auth_and_more"),
        ("token", "0016_alter_permission_token_auth"),
        ("token", "0017_tokenauth_identifier_alter_tokenauth_token"),
    ]

    initial = True

    dependencies = [
        ("core", "0001_initial_to_v360"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenAuth",
            fields=[
                (
                    "token",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="token",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        help_text="Name of the person in the organization who can access the API",
                        max_length=200,
                        verbose_name="contact person",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email of the person, who can access the API",
                        max_length=254,
                        verbose_name="email",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Organizations which has an access to the API",
                        max_length=200,
                        verbose_name="organization",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last date when the token was modified",
                        verbose_name="last modified",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the token was created",
                        verbose_name="created",
                    ),
                ),
                (
                    "administration",
                    models.CharField(
                        blank=True,
                        help_text="Administration which has an access to the API",
                        max_length=200,
                        verbose_name="administration",
                    ),
                ),
                (
                    "application",
                    models.CharField(
                        blank=True,
                        help_text="Application which has an access to the API",
                        max_length=200,
                        verbose_name="application",
                    ),
                ),
            ],
            options={
                "verbose_name": "token authorization",
                "verbose_name_plural": "token authorizations",
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("read_only", "Read-only"),
                            ("read_and_write", "Read and write"),
                        ],
                        help_text="Permission mode",
                        max_length=20,
                        verbose_name="mode",
                    ),
                ),
                (
                    "object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="core.objecttype",
                    ),
                ),
                (
                    "old_token_auth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="token.tokenauth",
                    ),
                ),
                (
                    "use_fields",
                    models.BooleanField(
                        default=False,
                        help_text="Use field-based authorization",
                        verbose_name="use fields",
                    ),
                ),
                (
                    "fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Fields allowed for this token in relation to objecttype versions. Supports only first level of the `record.data` properties",
                        null=True,
                        verbose_name="mode",
                    ),
                ),
            ],
            options={
                "verbose_name": "permission",
                "verbose_name_plural": "permissions",
            },
        ),
        migrations.AddField(
            model_name="tokenauth",
            name="object_types",
            field=models.ManyToManyField(
                help_text="Object types which can be accessed",
                through="token.Permission",
                to="core.objecttype",
            ),
        ),
        migrations.AlterField(
            model_name="tokenauth",
            name="administration",
            field=models.CharField(
                blank=True,
                help_text="Administration which has access to the API",
                max_length=200,
                verbose_name="administration",
            ),
        ),
        migrations.AlterField(
            model_name="tokenauth",
            name="application",
            field=models.CharField(
                blank=True,
                help_text="Application which has access to the API",
                max_length=200,
                verbose_name="application",
            ),
        ),
        migrations.AlterField(
            model_name="tokenauth",
            name="organization",
            field=models.CharField(
                blank=True,
                help_text="Organization which has access to the API",
                max_length=200,
                verbose_name="organization",
            ),
        ),
        migrations.AddField(
            model_name="tokenauth",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has access to all objects.",
                verbose_name="is superuser",
            ),
        ),
        migrations.RenameModel(
            old_name="TokenAuth",
            new_name="OldTokenAuth",
        ),
        migrations.CreateModel(
            name="TokenAuth",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=40, verbose_name="token")),
                (
                    "contact_person",
                    models.CharField(
                        help_text="Name of the person in the organization who can access the API",
                        max_length=200,
                        verbose_name="contact person",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email of the person, who can access the API",
                        max_length=254,
                        verbose_name="email",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Organization which has access to the API",
                        max_length=200,
                        verbose_name="organization",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last date when the token was modified",
                        verbose_name="last modified",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the token was created",
                        verbose_name="created",
                    ),
                ),
                (
                    "application",
                    models.CharField(
                        blank=True,
                        help_text="Application which has access to the API",
                        max_length=200,
                        verbose_name="application",
                    ),
                ),
                (
                    "administration",
                    models.CharField(
                        blank=True,
                        help_text="Administration which has access to the API",
                        max_length=200,
                        verbose_name="administration",
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user has access to all objects.",
                        verbose_name="is superuser",
                    ),
                ),
                (
                    "object_types",
                    models.ManyToManyField(
                        help_text="Object types which can be accessed",
                        through="token.Permission",
                        to="core.objecttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "token authorization",
                "verbose_name_plural": "token authorizations",
            },
        ),
        migrations.AddField(
            model_name="permission",
            name="new_token_auth",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permissions",
                to="token.tokenauth",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="permission",
            unique_together={("new_token_auth", "object_type")},
        ),
        migrations.RemoveField(
            model_name="permission",
            name="old_token_auth",
        ),
        migrations.DeleteModel(
            name="OldTokenAuth",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="new_token_auth",
            new_name="token_auth",
        ),
        migrations.AlterUniqueTogether(
            name="permission",
            unique_together={("token_auth", "object_type")},
        ),
        migrations.AlterField(
            model_name="permission",
            name="token_auth",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="token.tokenauth",
            ),
        ),
        migrations.AlterField(
            model_name="tokenauth",
            name="token",
            field=models.CharField(max_length=40, unique=True, verbose_name="token"),
        ),
        migrations.AddField(
            model_name="tokenauth",
            name="identifier",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tokenauth",
            name="identifier",
            field=models.SlugField(
                help_text="A human-friendly label to refer to this token",
                unique=True,
                validators=[objects.token.validators.validate_no_empty],
            ),
        ),
        migrations.AlterField(
            model_name="tokenauth",
            name="token",
            field=models.CharField(
                max_length=40,
                unique=True,
                validators=[
                    objects.token.validators.validate_no_empty,
                    objects.token.validators.validate_no_whitespace,
                ],
                verbose_name="token",
            ),
        ),
    ]
