# Generated by Django 2.2.12 on 2020-12-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TokenAuth",
            fields=[
                (
                    "token",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="token",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        help_text="Name of the person in the organization who can access the API",
                        max_length=200,
                        verbose_name="contact person",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email of the person, who can access the API",
                        max_length=254,
                        verbose_name="email",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Organizations which has an access to the API",
                        max_length=200,
                        verbose_name="organization",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last date when the token was modified",
                        verbose_name="last modified",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the token was created",
                        verbose_name="created",
                    ),
                ),
            ],
            options={
                "verbose_name": "token authorization",
                "verbose_name_plural": "token authorizations",
            },
        ),
    ]
