# Generated by Django 2.2.12 on 2020-12-23 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_auto_20201222_1833"),
        ("token", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("read_only", "Read-only"),
                            ("read_and_write", "Read and write"),
                        ],
                        help_text="Permission mode",
                        max_length=20,
                        verbose_name="mode",
                    ),
                ),
                (
                    "object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="core.ObjectType",
                    ),
                ),
                (
                    "token_auth",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="token.TokenAuth",
                    ),
                ),
            ],
            options={
                "verbose_name": "permission",
                "verbose_name_plural": "permissions",
            },
        ),
        migrations.AddField(
            model_name="tokenauth",
            name="object_types",
            field=models.ManyToManyField(
                help_text="Objecttypes which can be accessed",
                through="token.Permission",
                to="core.ObjectType",
            ),
        ),
    ]
