# Generated by Django 2.2.12 on 2021-03-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("token", "0002_auto_20201223_1231"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenauth",
            name="administration",
            field=models.CharField(
                blank=True,
                help_text="Administration which has an access to the API",
                max_length=200,
                verbose_name="administration",
            ),
        ),
        migrations.AddField(
            model_name="tokenauth",
            name="application",
            field=models.CharField(
                blank=True,
                help_text="Application which has an access to the API",
                max_length=200,
                verbose_name="application",
            ),
        ),
        migrations.AlterField(
            model_name="tokenauth",
            name="object_types",
            field=models.ManyToManyField(
                help_text="Object types which can be accessed",
                through="token.Permission",
                to="core.ObjectType",
            ),
        ),
    ]
