# Generated by Django 2.2.12 on 2021-03-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("token", "0003_auto_20210312_1507"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenauth",
            name="administration",
            field=models.CharField(
                blank=True,
                help_text="Administration which has access to the API",
                max_length=200,
                verbose_name="administration",
            ),
        ),
        migrations.AlterField(
            model_name="tokenauth",
            name="application",
            field=models.CharField(
                blank=True,
                help_text="Application which has access to the API",
                max_length=200,
                verbose_name="application",
            ),
        ),
        migrations.AlterField(
            model_name="tokenauth",
            name="organization",
            field=models.CharField(
                blank=True,
                help_text="Organization which has access to the API",
                max_length=200,
                verbose_name="organization",
            ),
        ),
    ]
