# Generated by Django 2.2.24 on 2021-07-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20201222_1833'),
        ('token', '0005_auto_20210623_1242'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('token_auth', 'object_type')},
        ),
    ]
