# Generated by Django 2.2.24 on 2021-07-28 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("token", "0006_auto_20210721_1543"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permission",
            name="fields",
        ),
    ]
