# Generated by Django 3.2 on 2023-06-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("token", "0008_permission_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Fields allowed for this token in relation to objecttype versions. Supports only first level of the `record.data` properties",
                null=True,
                verbose_name="mode",
            ),
        ),
    ]
