# Generated by Django 3.2.23 on 2024-03-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("token", "0009_alter_permission_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenauth",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has access to all objects.",
                verbose_name="is superuser",
            ),
        ),
    ]
