# Generated by Django 4.2.11 on 2024-05-02 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_objectrecord_data"),
        ("token", "0009_alter_permission_fields"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TokenAuth",
            new_name="OldTokenAuth",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="token_auth",
            new_name="old_token_auth",
        ),
        migrations.AlterUniqueTogether(
            name="permission",
            unique_together={("old_token_auth", "object_type")},
        ),
    ]
