# Generated by Django 4.2.11 on 2024-05-02 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_objectrecord_data"),
        ("token", "0011_rename_tokenauth_oldtokenauth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenAuth",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=40, verbose_name="token")),
                (
                    "contact_person",
                    models.CharField(
                        help_text="Name of the person in the organization who can access the API",
                        max_length=200,
                        verbose_name="contact person",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email of the person, who can access the API",
                        max_length=254,
                        verbose_name="email",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Organization which has access to the API",
                        max_length=200,
                        verbose_name="organization",
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last date when the token was modified",
                        verbose_name="last modified",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the token was created",
                        verbose_name="created",
                    ),
                ),
                (
                    "application",
                    models.CharField(
                        blank=True,
                        help_text="Application which has access to the API",
                        max_length=200,
                        verbose_name="application",
                    ),
                ),
                (
                    "administration",
                    models.CharField(
                        blank=True,
                        help_text="Administration which has access to the API",
                        max_length=200,
                        verbose_name="administration",
                    ),
                ),
                (
                    "object_types",
                    models.ManyToManyField(
                        help_text="Object types which can be accessed",
                        through="token.Permission",
                        to="core.objecttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "token authorization",
                "verbose_name_plural": "token authorizations",
            },
        ),
        migrations.AddField(
            model_name="permission",
            name="new_token_auth",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permissions",
                to="token.tokenauth",
            ),
        ),
    ]
