# Generated by Django 4.2.11 on 2024-05-02 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_objectrecord_data"),
        ("token", "0013_copy_token_auth"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="permission",
            unique_together={("new_token_auth", "object_type")},
        ),
        migrations.RemoveField(
            model_name="permission",
            name="old_token_auth",
        ),
        migrations.DeleteModel(
            name="OldTokenAuth",
        ),
    ]
