# Generated by Django 4.2.11 on 2024-05-02 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("token", "0015_rename_new_token_auth_permission_token_auth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="token_auth",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="token.tokenauth",
            ),
        ),
        migrations.AlterField(
            model_name="tokenauth",
            name="token",
            field=models.CharField(
                db_index=True,
                max_length=40,
                verbose_name="token"
            ),
        ),
    ]
