# Generated by Django 2.2.12 on 2020-04-15 12:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "object_type",
                    models.URLField(
                        help_text="Url reference to OBJECTTYPE in Objecttypes API",
                        verbose_name="object type",
                    ),
                ),
                (
                    "version",
                    models.SmallIntegerField(
                        help_text="Version of the OBJECTTYPE", verbose_name="version"
                    ),
                ),
                (
                    "data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default={},
                        help_text="Object data, based on OBJECTTYPE",
                        verbose_name="data",
                    ),
                ),
            ],
        ),
    ]
