# Generated by Django 5.2.11 on 2026-03-23 14:23

import datetime
import uuid

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("core", "0001_initial"),
        ("core", "0002_auto_20200518_1707"),
        ("core", "0003_objectrecord"),
        ("core", "0004_move_data_to_record"),
        ("core", "0005_remove_object_data"),
        ("core", "0006_auto_20200904_1402"),
        ("core", "0007_auto_20200904_1403"),
        ("core", "0008_objectrecord_correct"),
        ("core", "0009_objectrecord_version"),
        ("core", "0010_move_version_to_record"),
        ("core", "0011_remove_object_version"),
        ("core", "0012_objectrecord_uuid"),
        ("core", "0013_generate_record_uuids"),
        ("core", "0014_auto_20200915_1740"),
        ("core", "0015_objectrecord_geometry"),
        ("core", "0016_auto_20210111_1649"),
        ("core", "0017_auto_20210111_1653"),
        ("core", "0018_auto_20210113_1239"),
        ("core", "0019_fill_record_index"),
        ("core", "0020_auto_20210118_1117"),
        ("core", "0021_auto_20201222_1745"),
        ("core", "0022_move_object_types_to_separate_model"),
        ("core", "0023_remove_object_object_type"),
        ("core", "0024_auto_20201222_1811"),
        ("core", "0025_delete_objects_with_empty_object_type"),
        ("core", "0026_auto_20201222_1833"),
        ("core", "0027_auto_20211203_1209"),
        ("core", "0028_alter_objectrecord_data"),
        ("core", "0029_alter_object_object_type"),
        ("core", "0030_objectrecord_idx_objectrecord_data_gin"),
        ("core", "0031_object_created_on_object_modified_on_and_more"),
        ("core", "0032_objectrecord__object_type"),
        ("core", "0033_objectrecord__backfill_denormalized_fields"),
        ("core", "0034_alter_objectrecord__object_type_and_more"),
        ("core", "0035_objecttype_allow_geometry_objecttype_contact_email_and_more"),
        ("core", "0036_objecttype_is_imported"),
        ("core", "0037_reference"),
        ("core", "0038_remove_objecttype_linkable_to_zaken"),
        ("core", "0039_alter_objecttype_unique_together_and_more"),
    ]

    initial = True

    dependencies = [
        ("zgw_consumers", "0011_remove_service_extra"),
    ]

    operations = [
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "object_type",
                    models.URLField(
                        help_text="Url reference to OBJECTTYPE in Objecttypes API",
                        verbose_name="object type",
                    ),
                ),
                (
                    "version",
                    models.PositiveSmallIntegerField(
                        help_text="Version of the OBJECTTYPE", verbose_name="version"
                    ),
                ),
                (
                    "data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict,
                        help_text="Object data, based on OBJECTTYPE",
                        verbose_name="data",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObjectRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict,
                        help_text="Object data, based on OBJECTTYPE",
                        verbose_name="data",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("changed", "Changed"),
                            ("destroyed", "Destroyed"),
                        ],
                        default="created",
                        max_length=50,
                        verbose_name="record type",
                    ),
                ),
                (
                    "material_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="material date"
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(verbose_name="registration date"),
                ),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="core.object",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="object",
            name="data",
        ),
        migrations.RenameField(
            model_name="objectrecord",
            old_name="material_date",
            new_name="start_date",
        ),
        migrations.RemoveField(
            model_name="objectrecord",
            name="record_type",
        ),
        migrations.AddField(
            model_name="objectrecord",
            name="end_date",
            field=models.DateField(
                help_text="Legal end date of the object record",
                null=True,
                verbose_name="end date",
            ),
        ),
        migrations.AlterField(
            model_name="objectrecord",
            name="registration_date",
            field=models.DateField(
                default=datetime.date.today,
                help_text="The date when the record was registered in the system",
                verbose_name="registration date",
            ),
        ),
        migrations.AlterField(
            model_name="objectrecord",
            name="start_date",
            field=models.DateField(
                help_text="Legal start date of the object record",
                verbose_name="start date",
            ),
        ),
        migrations.AddField(
            model_name="objectrecord",
            name="correct",
            field=models.OneToOneField(
                blank=True,
                help_text="Object record which corrects the current record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="corrected",
                to="core.objectrecord",
            ),
        ),
        migrations.AddField(
            model_name="objectrecord",
            name="version",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Version of the OBJECTTYPE for data in the object record",
                verbose_name="version",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="object",
            name="version",
        ),
        migrations.AddField(
            model_name="objectrecord",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, help_text="Unique identifier (UUID4)", null=True
            ),
        ),
        migrations.RemoveField(
            model_name="objectrecord",
            name="uuid",
        ),
        migrations.AddField(
            model_name="objectrecord",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True,
                help_text="Point, linestring or polygon object which represents the coordinates of the object",
                null=True,
                srid=4326,
                verbose_name="geometry",
            ),
        ),
        migrations.RenameField(
            model_name="objectrecord",
            old_name="end_date",
            new_name="end_at",
        ),
        migrations.RenameField(
            model_name="objectrecord",
            old_name="registration_date",
            new_name="registration_at",
        ),
        migrations.RenameField(
            model_name="objectrecord",
            old_name="start_date",
            new_name="start_at",
        ),
        migrations.AlterField(
            model_name="objectrecord",
            name="correct",
            field=models.OneToOneField(
                blank=True,
                help_text="Object record which corrects the current record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="corrected",
                to="core.objectrecord",
                verbose_name="correction for",
            ),
        ),
        migrations.AlterField(
            model_name="objectrecord",
            name="end_at",
            field=models.DateField(
                help_text="Legal end date of the object record",
                null=True,
                verbose_name="end at",
            ),
        ),
        migrations.AlterField(
            model_name="objectrecord",
            name="registration_at",
            field=models.DateField(
                default=datetime.date.today,
                help_text="The date when the record was registered in the system",
                verbose_name="registration at",
            ),
        ),
        migrations.AlterField(
            model_name="objectrecord",
            name="start_at",
            field=models.DateField(
                help_text="Legal start date of the object record",
                verbose_name="start at",
            ),
        ),
        migrations.AddField(
            model_name="objectrecord",
            name="index",
            field=models.PositiveIntegerField(
                default=1, help_text="Incremental index number of the object record."
            ),
        ),
        migrations.AlterUniqueTogether(
            name="objectrecord",
            unique_together={("object", "index")},
        ),
        migrations.AlterField(
            model_name="objectrecord",
            name="correct",
            field=models.OneToOneField(
                blank=True,
                help_text="Object record which corrects the current record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="corrected",
                to="core.objectrecord",
                verbose_name="correction for",
            ),
        ),
        migrations.CreateModel(
            name="ObjectType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        help_text="Unique identifier (UUID4) of the OBJECTTYPE in Objecttypes API"
                    ),
                ),
                (
                    "_name",
                    models.CharField(
                        help_text="Cached name of the objecttype retrieved from the Objecttype API",
                        max_length=100,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="object_types",
                        to="zgw_consumers.service",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="object",
            name="object_type_fk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.objecttype",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="object",
            name="object_type",
        ),
        migrations.RenameField(
            model_name="object",
            old_name="object_type_fk",
            new_name="object_type",
        ),
        migrations.AlterField(
            model_name="objectrecord",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True,
                help_text="Point, linestring or polygon object which represents the coordinates of the object. Geometry can be added only if the related OBJECTTYPE allows this (`OBJECTTYPE.allowGeometry = true` or `OBJECTTYPE.allowGeometry` doesn't exist)",
                null=True,
                srid=4326,
                verbose_name="geometry",
            ),
        ),
        migrations.AlterField(
            model_name="objectrecord",
            name="data",
            field=models.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Object data, based on OBJECTTYPE",
                verbose_name="data",
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="object_type",
            field=models.ForeignKey(
                help_text="OBJECTTYPE in Objecttypes API",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.objecttype",
            ),
        ),
        migrations.AddIndex(
            model_name="objectrecord",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["data"], name="idx_objectrecord_data_gin"
            ),
        ),
        migrations.AddField(
            model_name="object",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Creation date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="object",
            name="modified_on",
            field=models.DateTimeField(
                auto_now=True, help_text="Last modification date"
            ),
        ),
        migrations.AddField(
            model_name="objectrecord",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Creation date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="objectrecord",
            name="modified_on",
            field=models.DateTimeField(
                auto_now=True, help_text="Last modification date"
            ),
        ),
        migrations.AddField(
            model_name="objectrecord",
            name="_object_type",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                help_text="OBJECTTYPE in Objecttypes API",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.objecttype",
            ),
        ),
        migrations.AlterField(
            model_name="objectrecord",
            name="_object_type",
            field=models.ForeignKey(
                help_text="OBJECTTYPE in Objecttypes API",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.objecttype",
            ),
        ),
        migrations.AddIndex(
            model_name="objectrecord",
            index=models.Index(
                fields=["_object_type_id", "-index"], name="idx_objectrecord_type_index"
            ),
        ),
        migrations.AddIndex(
            model_name="objectrecord",
            index=models.Index(
                fields=["_object_type_id", "id"], name="idx_objectrecord_type_id"
            ),
        ),
        migrations.AddIndex(
            model_name="objectrecord",
            index=models.Index(
                fields=["_object_type_id", "start_at", "end_at", "object", "-index"],
                name="idx_type_start_end_object_idx",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="allow_geometry",
            field=models.BooleanField(
                default=True,
                help_text="Shows whether the related objects can have geographic coordinates. If the value is 'false' the related objects are not allowed to have coordinates and the creation/update of objects with `geometry` property will raise an error ",
                verbose_name="allow geometry",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="contact_email",
            field=models.CharField(
                blank=True,
                help_text="Email of the person in the organization who can provide information about the object type",
                max_length=200,
                verbose_name="contact email",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="contact_person",
            field=models.CharField(
                blank=True,
                help_text="Name of the person in the organization who can provide information about the object type",
                max_length=200,
                verbose_name="contact person",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="created_at",
            field=models.DateField(
                blank=True,
                help_text="Date when the object type was created",
                null=True,
                verbose_name="created at",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="data_classification",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("intern", "Intern"),
                    ("confidential", "Confidential"),
                    ("strictly_confidential", "Strictly confidential"),
                ],
                default="open",
                help_text="Confidential level of the object type",
                max_length=50,
                verbose_name="data classification",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="The description of the object type",
                max_length=1000,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="documentation_url",
            field=models.URLField(
                blank=True,
                help_text="Link to the documentation for the object type",
                verbose_name="documentation url",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="labels",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Key-value pairs of keywords related for the object type",
                verbose_name="labels",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="maintainer_department",
            field=models.CharField(
                blank=True,
                help_text="Business department which is responsible for the object type",
                max_length=200,
                verbose_name="maintainer department",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="maintainer_organization",
            field=models.CharField(
                blank=True,
                help_text="Organization which is responsible for the object type",
                max_length=200,
                verbose_name="maintainer organization",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="modified_at",
            field=models.DateField(
                blank=True,
                help_text="Last date when the object type was modified",
                null=True,
                verbose_name="modified at",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name of the object type",
                max_length=100,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="name_plural",
            field=models.CharField(
                blank=True,
                help_text="Plural name of the object type",
                max_length=100,
                verbose_name="name plural",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="provider_organization",
            field=models.CharField(
                blank=True,
                help_text="Organization which is responsible for publication of the object type",
                max_length=200,
                verbose_name="provider organization",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Name of the system from which the object type originates",
                max_length=200,
                verbose_name="source",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="update_frequency",
            field=models.CharField(
                choices=[
                    ("real_time", "Real-time"),
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="Indicates how often the object type is updated",
                max_length=10,
                verbose_name="update frequency",
            ),
        ),
        migrations.AddField(
            model_name="objecttype",
            name="is_imported",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Is imported"
            ),
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(choices=[("zaak", "Zaak")], max_length=4)),
                ("url", models.URLField()),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="core.objectrecord",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["url"], name="core_refere_url_a2dbbb_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("record", "url"), name="unique_ref_url"
                    )
                ],
            },
        ),
        migrations.AlterField(
            model_name="object",
            name="object_type",
            field=models.ForeignKey(
                help_text="OBJECTTYPE",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.objecttype",
            ),
        ),
        migrations.AlterField(
            model_name="objectrecord",
            name="_object_type",
            field=models.ForeignKey(
                help_text="OBJECTTYPE",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.objecttype",
            ),
        ),
        migrations.AlterField(
            model_name="objecttype",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date when the object type was created",
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="objecttype",
            name="modified_at",
            field=models.DateField(
                auto_now=True,
                default=django.utils.timezone.now,
                help_text="Last date when the object type was modified",
                verbose_name="modified at",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="objecttype",
            name="name",
            field=models.CharField(
                help_text="Name of the object type", max_length=100, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="objecttype",
            name="name_plural",
            field=models.CharField(
                help_text="Plural name of the object type",
                max_length=100,
                verbose_name="name plural",
            ),
        ),
        migrations.AlterField(
            model_name="objecttype",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, help_text="Unique identifier (UUID4)", unique=True
            ),
        ),
        migrations.CreateModel(
            name="ObjectTypeVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveSmallIntegerField(
                        help_text="Integer version of the OBJECTTYPE",
                        verbose_name="version",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Date when the version was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified_at",
                    models.DateField(
                        auto_now=True,
                        help_text="Last date when the version was modified",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "published_at",
                    models.DateField(
                        blank=True,
                        help_text="Date when the version was published",
                        null=True,
                        verbose_name="published_at",
                    ),
                ),
                (
                    "json_schema",
                    models.JSONField(
                        default=dict,
                        help_text="JSON schema for Object validation",
                        verbose_name="JSON schema",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("draft", "Draft"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="draft",
                        help_text="Status of the object type version",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "object_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="core.objecttype",
                    ),
                ),
            ],
            options={
                "unique_together": {("object_type", "version")},
            },
        ),
        migrations.RemoveField(
            model_name="objecttype",
            name="_name",
        ),
        migrations.RemoveField(
            model_name="objecttype",
            name="service",
        ),
    ]
