# Generated by Django 2.2.12 on 2020-09-03 14:26

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20200518_1707"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict,
                        help_text="Object data, based on OBJECTTYPE",
                        verbose_name="data",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("changed", "Changed"),
                            ("destroyed", "Destroyed"),
                        ],
                        default="created",
                        max_length=50,
                        verbose_name="record type",
                    ),
                ),
                (
                    "material_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="material date"
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(verbose_name="registration date"),
                ),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="core.Object",
                    ),
                ),
            ],
        ),
    ]
