# Generated by Django 2.2.12 on 2020-09-04 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_object_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="objectrecord", old_name="material_date", new_name="start_date"
        ),
        migrations.RemoveField(
            model_name="objectrecord",
            name="record_type",
        ),
        migrations.AddField(
            model_name="objectrecord",
            name="end_date",
            field=models.DateField(
                help_text="Legal end date of the object record",
                null=True,
                verbose_name="end date",
            ),
        ),
        migrations.AlterField(
            model_name="objectrecord",
            name="registration_date",
            field=models.DateField(
                default=datetime.date.today,
                help_text="The date when the record was registered in the system",
                verbose_name="registration date",
            ),
        ),
    ]
