# Generated by Django 2.2.12 on 2020-09-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_auto_20200904_1402"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectrecord",
            name="start_date",
            field=models.DateField(
                help_text="Legal start date of the object record",
                verbose_name="start date",
            ),
        ),
    ]
