# Generated by Django 2.2.12 on 2020-09-04 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_auto_20200904_1403"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectrecord",
            name="correct",
            field=models.OneToOneField(
                blank=True,
                help_text="Object record which corrects the current record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="corrected",
                to="core.ObjectRecord",
            ),
        ),
    ]
