# Generated by Django 2.2.12 on 2020-09-22 13:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_auto_20200915_1740"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectrecord",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True,
                help_text="Point, linestring or polygon object which represents the coordinates of the object",
                null=True,
                srid=4326,
                verbose_name="geometry",
            ),
        ),
    ]
