# Generated by Django 2.2.12 on 2021-01-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_auto_20210111_1653"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objectrecord",
            name="uuid",
        ),
        migrations.AddField(
            model_name="objectrecord",
            name="index",
            field=models.PositiveIntegerField(
                default=1, help_text="Incremental index number of the object record."
            ),
        ),
    ]
