# Generated by Django 2.2.12 on 2021-01-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_fill_record_index'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='objectrecord',
            unique_together={('object', 'index')},
        ),
    ]
