# Generated by Django 2.2.12 on 2020-12-22 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_delete_objects_with_empty_object_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="object_type",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.ObjectType",
            ),
            preserve_default=False,
        ),
    ]
