# Generated by Django 2.2.24 on 2021-09-20 14:02

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_auto_20201222_1833"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectrecord",
            name="_cached_data",
            field=models.TextField(
                help_text="JSON data converted to the text blob for search purposes.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="objectrecord",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Object data, based on OBJECTTYPE",
                verbose_name="data",
            ),
        ),
    ]
