# Generated by Django 2.2.24 on 2021-12-03 11:09

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_auto_20201222_1833"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectrecord",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Object data, based on OBJECTTYPE",
                verbose_name="data",
            ),
        ),
        migrations.AlterField(
            model_name="objectrecord",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True,
                help_text="Point, linestring or polygon object which represents the coordinates of the object. Geometry can be added only if the related OBJECTTYPE allows this (`OBJECTTYPE.canHaveGeometry = true` or `OBJECTTYPE.canHaveGeometry` doesn't exist)",
                null=True,
                srid=4326,
                verbose_name="geometry",
            ),
        ),
    ]
