# Generated by Django 2.2.28 on 2023-06-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_auto_20211203_1209"),
    ]

    operations = [
        migrations.AddField(
            model_name="objecttype",
            name="_version",
            field=models.IntegerField(
                blank=True,
                help_text="Cached version of the objecttype retrieved from the Objecttype API",
                null=True,
            ),
        ),
    ]
