# Generated by Django 2.2.28 on 2023-05-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_auto_20211203_1209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objecttype",
            name="_name",
            field=models.CharField(
                help_text="Cached name of the objecttype retrieved from the Objecttype API",
                max_length=100,
                unique=True,
            ),
        ),
    ]
