# Generated by Django 3.2 on 2023-06-14 08:05

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20211203_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectrecord',
            name='data',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Object data, based on OBJECTTYPE', verbose_name='data'),
        ),
    ]
