# Generated by Django 4.2.11 on 2024-08-12 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_objectrecord_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="object_type",
            field=models.ForeignKey(
                help_text="OBJECTTYPE in Objecttypes API",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.objecttype",
            ),
        ),
    ]
