# Generated by Django 2.2.24 on 2021-09-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_cache_data_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectrecord",
            name="_cached_data",
            field=models.TextField(
                default="",
                help_text="JSON data converted to the text blob for search purposes.",
            ),
            preserve_default=False,
        ),
    ]
