# Generated by Django 5.2.3 on 2025-09-09 08:24

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("core", "0029_alter_object_object_type"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="objectrecord",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["data"], name="idx_objectrecord_data_gin"
            ),
        ),
    ]
