# Generated by Django 5.2.3 on 2025-09-09 08:24

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('core', '0029_alter_object_object_type'),
    ]

    # NOTE the creation of this index has been moved to after the data migration done in
    # `0033_objectrecord__backfill_denormalized_fields`, to speed up the backfill process
    operations = []
