# Generated by Django 5.2.3 on 2025-09-19 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_objectrecord_idx_objectrecord_data_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text='Last modification date'),
        ),
        migrations.AddField(
            model_name='objectrecord',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Creation date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectrecord',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text='Last modification date'),
        ),
    ]
