# Generated by Django 5.2.3 on 2025-09-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_object_created_on_object_modified_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectrecord',
            name='_is_latest',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
