# Generated by Django 5.2.3 on 2025-09-29 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_object_created_on_object_modified_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectrecord",
            name="_object_type",
            field=models.ForeignKey(
                blank=True,
                help_text="OBJECTTYPE in Objecttypes API",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.objecttype",
            ),
        ),
    ]
