# Generated by Django 5.2.3 on 2025-09-29 08:19

import os
import threading
from datetime import datetime
import random
from time import sleep
from django.db import connection, migrations, transaction
from concurrent.futures import ThreadPoolExecutor
from structlog import get_logger

logger = get_logger(__name__)

# Shared counter and lock
records_processed = 0
counter_lock = threading.Lock()

# TODO estimate expected finish time instead
def estimate_total_time(start_time, current_time, processed_records: int):
    """
    Estimate the total duration of a job based on current progress.

    Args:
        total_records: Total number of records to process.
        start_time: Time when the job started.
        current_time: Current time.
        processed_records: Number of records processed so far.

    Returns:
        Estimated total duration as a timedelta.
    """
    # TODO actual count
    total_records = 3_800_000
    if processed_records == 0:
        # Avoid division by zero; we have no info yet
        return None

    elapsed_time = current_time - start_time
    fraction_done = float(processed_records) / float(total_records)
    total_time_estimate = elapsed_time / fraction_done
    # return start_time + total_time_estimate
    return total_time_estimate.seconds


BATCH_SIZE = int(os.getenv("OBJECTRECORD_BATCH_SIZE", 2_000))
# TODO configurable?
NUM_WORKERS = 4


def backfill_object_type_batch_concurrent(cursor):
    """
    Grab a batch of rows with _object_type_id IS NULL and update them.
    SKIP LOCKED ensures multiple workers won't update the same row.
    """
    # TODO how does this deal with rows being updated by other operations?
    cursor.execute("""
        WITH cte AS (
            SELECT r.id, o.object_type_id
            FROM core_objectrecord r
            JOIN core_object o ON r.object_id = o.id
            WHERE r._object_type_id IS NULL
            FOR UPDATE SKIP LOCKED
            LIMIT %s
        )
        UPDATE core_objectrecord r
        SET _object_type_id = cte.object_type_id
        FROM cte
        WHERE r.id = cte.id;
    """, [BATCH_SIZE])

    return cursor.rowcount


def worker(apps, start):
    """
    Worker that keeps grabbing batches until none are left.
    """
    global records_processed
    # Stagger the workers to avoid synchronized bursts of commit I/O
    delay = random.uniform(0.5, 1.5)
    sleep(delay)

    while True:
        with transaction.atomic():
            with connection.cursor() as cursor:
                cursor.execute("SET LOCAL synchronous_commit = OFF;")
                num_updated = backfill_object_type_batch_concurrent(cursor)
                current = datetime.now()

                with counter_lock:
                    records_processed += num_updated

                expected_end = estimate_total_time(start, current, records_processed)
                if num_updated == 0:
                    sleep(0.5)
                    break

                logger.info(
                    "backfilled_object_type_for_records",
                    expected_end=expected_end,
                    num_records=num_updated,
                    total=records_processed,
                )


def forward(apps, schema_editor):
    """
    Spin up NUM_WORKERS parallel workers to process the table concurrently.
    """
    start = datetime.now()
    with ThreadPoolExecutor(max_workers=NUM_WORKERS) as executor:
        futures = [executor.submit(worker, apps, start) for _ in range(NUM_WORKERS)]
        # Wait for all workers to finish
        for f in futures:
            f.result()


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("core", "0032_objectrecord__object_type"),
    ]

    # TODO MAKE SURE THIS WORKS FOR ALL MIGRATION PATHS
    # TODO make previous ginindex migration empty
    operations = [
        # Drop the GINIndex on data to improve speed for updates, rebuilding it after
        # the bulk update is faster
        migrations.RunSQL(
            "DROP INDEX CONCURRENTLY IF EXISTS idx_objectrecord_data_gin", migrations.RunSQL.noop
        ),
        migrations.RunPython(forward, migrations.RunPython.noop),
        # Re-add the index
        migrations.RunSQL(
            "CREATE INDEX CONCURRENTLY idx_objectrecord_data_gin "
            "ON core_objectrecord "
            "USING GIN (data);",
            migrations.RunSQL.noop
        )
    ]

# CREATE INDEX CONCURRENTLY IF NOT EXISTS core_objectrecord_object_id_idx ON core_objectrecord (id, object_id) WHERE _object_type_id IS NULL;

# CLUSTER core_objectrecord USING core_objectrecord_pkey;