# Generated by Django 5.2.3 on 2025-09-26 11:03

from django.db import migrations
from django.db.models import F, Window, Subquery, OuterRef
from django.db.models.functions import RowNumber

from structlog import get_logger

logger = get_logger(__name__)

def forward(apps, schema_editor):
    ObjectRecord = apps.get_model("core", "ObjectRecord")

    latest_index_subquery = ObjectRecord.objects.filter(
        object=OuterRef('object')
    ).order_by('-index').values('index')[:1]

    # Filter records that have that max index
    latest_records = ObjectRecord.objects.annotate(
        latest_index=Subquery(latest_index_subquery)
    ).filter(index=F('latest_index'))

    # TODO pick best size
    # batch_size = 50000
    # qs_ids = latest_records.values_list('id', flat=True)
    # for start in range(0, qs_ids.count(), batch_size):
    #     batch_ids = qs_ids[start:start + batch_size]
    #     ObjectRecord.objects.filter(id__in=batch_ids).update(_is_latest=True)

    #     logger.info("migration.object_records_is_latest_denormalized", index=start+batch_size)

    batch_size = 20000
    ids_iter = latest_records.values_list('id', flat=True).iterator(chunk_size=batch_size)

    num_processed = 0
    batch = []
    for pk in ids_iter:
        batch.append(pk)
        if len(batch) >= batch_size:
            ObjectRecord.objects.filter(id__in=batch).update(_is_latest=True)
            num_processed += len(batch)
            logger.info("migration.object_records_is_latest_denormalized", total_processed=num_processed)
            batch = []

    # final batch
    if batch:
        ObjectRecord.objects.filter(id__in=batch).update(_is_latest=True)
        logger.info("migration.object_records_is_latest_denormalized", total_processed=num_processed + len(batch))




class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_objectrecord__is_latest'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop)
    ]
