# Generated by Django 5.2.6 on 2025-10-02 09:37

import django.db.models.deletion
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("core", "0033_objectrecord__backfill_denormalized_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectrecord",
            name="_object_type",
            field=models.ForeignKey(
                db_index=True,
                help_text="OBJECTTYPE in Objecttypes API",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.objecttype",
            ),
        ),
        AddIndexConcurrently(
            model_name="objectrecord",
            index=models.Index(
                fields=["_object_type_id", "-index"], name="idx_objectrecord_type_index"
            ),
        ),
        AddIndexConcurrently(
            model_name="objectrecord",
            index=models.Index(
                fields=["_object_type_id", "id"], name="idx_objectrecord_type_id"
            ),
        ),
        AddIndexConcurrently(
            model_name="objectrecord",
            index=models.Index(
                fields=["_object_type_id", "start_at", "end_at", "object", "-index"],
                name="idx_type_start_end_object_idx",
            ),
        ),
    ]
