# Generated by Django 5.2.3 on 2025-09-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20250926_1401'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='objectrecord',
            index=models.Index(fields=['object', '_is_latest', 'start_at', 'end_at'], name='idx_record_index_start_end'),
        ),
    ]
