# Generated by Django 5.2.3 on 2025-09-26 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_objectrecord_idx_record_index_start_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectrecord',
            name='_object_type',
            field=models.ForeignKey(blank=True, help_text='OBJECTTYPE in Objecttypes API', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.objecttype'),
        ),
    ]
