# Generated by Django 5.2.7 on 2025-12-04 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_objectrecord__object_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttype',
            name='allow_geometry',
            field=models.BooleanField(default=True, help_text="Shows whether the related objects can have geographic coordinates. If the value is 'false' the related objects are not allowed to have coordinates and the creation/update of objects with `geometry` property will raise an error ", verbose_name='allow geometry'),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='contact_email',
            field=models.CharField(blank=True, help_text='Email of the person in the organization who can provide information about the object type', max_length=200, verbose_name='contact email'),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Name of the person in the organization who can provide information about the object type', max_length=200, verbose_name='contact person'),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='created_at',
            field=models.DateField(blank=True, help_text='Date when the object type was created', null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='data_classification',
            field=models.CharField(choices=[('open', 'Open'), ('intern', 'Intern'), ('confidential', 'Confidential'), ('strictly_confidential', 'Strictly confidential')], default='open', help_text='Confidential level of the object type', max_length=50, verbose_name='data classification'),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='description',
            field=models.CharField(blank=True, help_text='The description of the object type', max_length=1000, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='documentation_url',
            field=models.URLField(blank=True, help_text='Link to the documentation for the object type', verbose_name='documentation url'),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='labels',
            field=models.JSONField(blank=True, default=dict, help_text='Key-value pairs of keywords related for the object type', verbose_name='labels'),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='linkable_to_zaken',
            field=models.BooleanField(default=False, help_text='Objects of this type can have a link to 1 or more Zaken.\nTrue indicates the lifetime of the object is linked to the lifetime of linked zaken, i.e., when all linked Zaken to an object are archived/destroyed, the object will also be archived/destroyed.', verbose_name='linkable to zaken'),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='maintainer_department',
            field=models.CharField(blank=True, help_text='Business department which is responsible for the object type', max_length=200, verbose_name='maintainer department'),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='maintainer_organization',
            field=models.CharField(blank=True, help_text='Organization which is responsible for the object type', max_length=200, verbose_name='maintainer organization'),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='modified_at',
            field=models.DateField(blank=True, help_text='Last date when the object type was modified', null=True, verbose_name='modified at'),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the object type', max_length=100, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='name_plural',
            field=models.CharField(blank=True, help_text='Plural name of the object type', max_length=100, verbose_name='name plural'),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='provider_organization',
            field=models.CharField(blank=True, help_text='Organization which is responsible for publication of the object type', max_length=200, verbose_name='provider organization'),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='source',
            field=models.CharField(blank=True, help_text='Name of the system from which the object type originates', max_length=200, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='update_frequency',
            field=models.CharField(choices=[('real_time', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('unknown', 'Unknown')], default='unknown', help_text='Indicates how often the object type is updated', max_length=10, verbose_name='update frequency'),
        ),
        migrations.CreateModel(
            name='ObjectTypeVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(help_text='Integer version of the OBJECTTYPE', verbose_name='version')),
                ('created_at', models.DateField(blank=True, help_text='Date when the version was created', null=True, verbose_name='created at')),
                ('modified_at', models.DateField(blank=True, help_text='Last date when the version was modified', null=True, verbose_name='modified at')),
                ('published_at', models.DateField(blank=True, help_text='Date when the version was published', null=True, verbose_name='published_at')),
                ('json_schema', models.JSONField(default=dict, help_text='JSON schema for Object validation', verbose_name='JSON schema')),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('deprecated', 'Deprecated')], default='draft', help_text='Status of the object type version', max_length=20, verbose_name='status')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.objecttype')),
            ],
            options={
                'unique_together': {('object_type', 'version')},
            },
        ),
    ]
