# Generated by Django 5.2.3 on 2025-09-26 13:34

from django.db import migrations
from django.db.models import F, Window, Subquery, OuterRef
from django.db.models.functions import RowNumber


import structlog

logger= structlog.get_logger(__name__)

def forward(apps, schema_editor):
    ObjectRecord = apps.get_model("core", "ObjectRecord")
    Object = apps.get_model("core", "Object")

    last_id = None
    qs = ObjectRecord.objects.order_by("id").values_list("id", flat=True)
    BATCH_SIZE = 20_000

    total = 0

    while True:
        batch_ids = list(
            qs.filter(id__gt=last_id)[:BATCH_SIZE]
        ) if last_id else list(qs[:BATCH_SIZE])

        if not batch_ids:
            break

        # ORM-based update using subquery
        ObjectRecord.objects.filter(id__in=batch_ids).update(
            _object_type=Subquery(
                Object.objects.filter(
                    id=OuterRef("object_id")
                ).values("object_type_id")[:1]
            )
        )
        total += BATCH_SIZE
        logger.info("migration.object_records_type_denormalized", total_processed=total)
        last_id = batch_ids[-1]



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_objectrecord__object_type'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop)
    ]
