# Generated by Django 5.2.7 on 2025-12-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_objecttype_allow_geometry_objecttype_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttype',
            name='is_imported',
            field=models.BooleanField(default=False, editable=False, verbose_name='Is imported'),
        ),
    ]
