# Generated by Django 5.2.8 on 2026-01-08 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_objecttype_is_imported'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('zaak', 'Zaak')], max_length=4)),
                ('url', models.URLField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='core.objectrecord')),
            ],
            options={
                'indexes': [models.Index(fields=['url'], name='core_refere_url_a2dbbb_idx')],
                'constraints': [models.UniqueConstraint(fields=('record', 'url'), name='unique_ref_url')],
            },
        ),
    ]
