# Generated by Django 5.2.3 on 2025-09-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20250926_1534'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='objectrecord',
            index=models.Index(fields=['_object_type_id', '_is_latest', 'id'], name='idx_objectrecord_type_latest'),
        ),
    ]
