# Generated by Django 5.2.8 on 2026-01-27 14:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_reference'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='objecttype',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_type',
            field=models.ForeignKey(help_text='OBJECTTYPE', on_delete=django.db.models.deletion.PROTECT, to='core.objecttype'),
        ),
        migrations.AlterField(
            model_name='objectrecord',
            name='_object_type',
            field=models.ForeignKey(help_text='OBJECTTYPE', on_delete=django.db.models.deletion.PROTECT, to='core.objecttype'),
        ),
        migrations.AlterField(
            model_name='objecttype',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date when the object type was created', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objecttype',
            name='modified_at',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now, help_text='Last date when the object type was modified', verbose_name='modified at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objecttype',
            name='name',
            field=models.CharField(help_text='Name of the object type', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='objecttype',
            name='name_plural',
            field=models.CharField(help_text='Plural name of the object type', max_length=100, verbose_name='name plural'),
        ),
        migrations.AlterField(
            model_name='objecttype',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique identifier (UUID4)', unique=True),
        ),
        migrations.AlterField(
            model_name='objecttypeversion',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date when the version was created', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objecttypeversion',
            name='modified_at',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now, help_text='Last date when the version was modified', verbose_name='modified at'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='objecttype',
            name='_name',
        ),
        migrations.RemoveField(
            model_name='objecttype',
            name='service',
        ),
    ]
