# Generated by Django 5.2.8 on 2026-01-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objecttype',
            name='linkable_to_zaken',
        ),
    ]
