# Generated by Django 2.2.12 on 2020-10-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_type",
                    models.URLField(
                        help_text="Url reference to OBJECTTYPE in Objecttypes API",
                        verbose_name="object type",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("read_only", "Read-only"),
                            ("read_and_write", "Read and write"),
                        ],
                        help_text="Permission mode",
                        max_length=20,
                        verbose_name="mode",
                    ),
                ),
            ],
            options={
                "verbose_name": "object permission",
                "verbose_name_plural": "object permissions",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="object_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="accounts.ObjectPermission"
            ),
        ),
    ]
