# Generated by Django 2.2.12 on 2020-12-23 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_auto_20201012_1522"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="object_permissions",
        ),
        migrations.DeleteModel(
            name="ObjectPermission",
        ),
    ]
