name: check-oas

on:
  push:
  workflow_dispatch:

jobs:
  open-api-workflow-check-oas:
    uses: maykinmedia/open-api-workflows/.github/workflows/oas-check.yml@v5.0.0
    with:
      schema-path: 'src/objects/api/v2/openapi.yaml'
      schema-options: 'src/objects/api/v2/openapi.yaml'
      python-version: '3.11'
      django-settings-module: 'objects.conf.ci'
      apt-packages: 'libgdal-dev gdal-bin'
